sudo: false
cache: pip

language: python

python:
    - 3.6

stages:
  - lint
  - docs
  - test

jobs:
  include:
    # lint stage
    - stage: lint
    - env: TOXENV=flake8
    - env: TOXENV=pyroma

    # docs stage
    - stage: docs
    - env: TOXENV=readme

    # test stage
    - stage: test
    - env: TOXENV=py

matrix:
  allow_failures:
      - env: TOXENV=flake8
      - env: TOXENV=pyroma

install:
    - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov; else pip install tox; fi'

script:
    - tox

after_success:
    - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'
